#!/bin/bash

# primitive interval timer

file="$1"

function print_banner {
	figlet -f banner "$1" | tr '#' '\2588'
}

function print_time {
	num=$1
	hour=0
	min=0
	sec=0
	if ((num>59)); then
		((sec=num%60))
		((min=num/60))
		if ((min>59)); then
			((min=min%60))
			((hour=num/3600))
		fi
	else
		((sec=num))
	fi
	# print time as $hour : $min: $sec
	if ((hour>0)); then
		print_banner "$hour : $min : $sec"
	else
		if ((min>0)); then
			print_banner "$min : $sec"
		else
			print_banner "$sec"
		fi
	fi
}

while read xx yy; do
	# update console every second for xx seconds while doing countdown
	secs=$xx
	while [ $secs -gt 0 ]; do
		clear
		print_banner "$yy"
		print_time "$secs"
		sleep 1
		: $((secs--))
	done
        # make beep
        echo -e "\a"
done < $file
